const GO_TO_LOGIN = 'GO_TO_LOGIN'
const GO_TO_REGISTRATION = 'GO_TO_REGISTRATION'
const GO_TO_FORGOT_PASSWORD = 'GO_TO_FORGOT_PASSWORD'

const indexDirectory = {
    LOGIN: 0,
    REGISTRATION: 1,
    FORGOT_PASSWORD: 2,
}

export { GO_TO_LOGIN, GO_TO_REGISTRATION, GO_TO_FORGOT_PASSWORD, indexDirectory }
